trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'windows-latest'

variables:
  appName: 'Web-Application' # Replace with your Azure Web App name
  azureSubscription: 'Azure for Students' # Replace with your Azure subscription
  packagePath: 'target/*.jar'

stages:
- stage: Build
  displayName: 'Build and Test'
  jobs:
  - job: Build
    displayName: 'Build the application'
    steps:
    - task: UseJavaVersion@1
      inputs:
        version: '17'
        distribution: 'Microsoft'

    - task: Maven@3
      inputs:
        goals: 'clean install'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(System.DefaultWorkingDirectory)/target'
        artifactName: 'drop'

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    displayName: 'Web-Application'
    environment: 'Production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: 'drop'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webApp'
              appName: '$(appName)'
              package: '$(System.DefaultWorkingDirectory)/drop/*.jar'
